/* ══════════════════════════════════════════
   ARCANUM — Card Image Mapping  |  deck.js
   Maps card names → deck-images/*.jpg
   ══════════════════════════════════════════ */

const CARD_IMAGES = {
  // Major Arcana
  "The Fool": "deck-images/m00.jpg",
  "The Magician": "deck-images/m01.jpg",
  "The High Priestess": "deck-images/m02.jpg",
  "The Empress": "deck-images/m03.jpg",
  "The Emperor": "deck-images/m04.jpg",
  "The Hierophant": "deck-images/m05.jpg",
  "The Lovers": "deck-images/m06.jpg",
  "The Chariot": "deck-images/m07.jpg",
  Strength: "deck-images/m08.jpg",
  "The Hermit": "deck-images/m09.jpg",
  "Wheel of Fortune": "deck-images/m10.jpg",
  Justice: "deck-images/m11.jpg",
  "The Hanged Man": "deck-images/m12.jpg",
  Death: "deck-images/m13.jpg",
  Temperance: "deck-images/m14.jpg",
  "The Devil": "deck-images/m15.jpg",
  "The Tower": "deck-images/m16.jpg",
  "The Star": "deck-images/m17.jpg",
  "The Moon": "deck-images/m18.jpg",
  "The Sun": "deck-images/m19.jpg",
  Judgement: "deck-images/m20.jpg",
  "The World": "deck-images/m21.jpg",
  // Cups
  "Ace of Cups": "deck-images/c01.jpg",
  "Two of Cups": "deck-images/c02.jpg",
  "Three of Cups": "deck-images/c03.jpg",
  "Four of Cups": "deck-images/c04.jpg",
  "Five of Cups": "deck-images/c05.jpg",
  "Six of Cups": "deck-images/c06.jpg",
  "Seven of Cups": "deck-images/c07.jpg",
  "Eight of Cups": "deck-images/c08.jpg",
  "Nine of Cups": "deck-images/c09.jpg",
  "Ten of Cups": "deck-images/c10.jpg",
  "Page of Cups": "deck-images/c11.jpg",
  "Knight of Cups": "deck-images/c12.jpg",
  "Queen of Cups": "deck-images/c13.jpg",
  "King of Cups": "deck-images/c14.jpg",
  // Swords
  "Ace of Swords": "deck-images/s01.jpg",
  "Two of Swords": "deck-images/s02.jpg",
  "Three of Swords": "deck-images/s03.jpg",
  "Four of Swords": "deck-images/s04.jpg",
  "Five of Swords": "deck-images/s05.jpg",
  "Six of Swords": "deck-images/s06.jpg",
  "Seven of Swords": "deck-images/s07.jpg",
  "Eight of Swords": "deck-images/s08.jpg",
  "Nine of Swords": "deck-images/s09.jpg",
  "Ten of Swords": "deck-images/s10.jpg",
  "Page of Swords": "deck-images/s11.jpg",
  "Knight of Swords": "deck-images/s12.jpg",
  "Queen of Swords": "deck-images/s13.jpg",
  "King of Swords": "deck-images/s14.jpg",
  // Wands
  "Ace of Wands": "deck-images/w01.jpg",
  "Two of Wands": "deck-images/w02.jpg",
  "Three of Wands": "deck-images/w03.jpg",
  "Four of Wands": "deck-images/w04.jpg",
  "Five of Wands": "deck-images/w05.jpg",
  "Six of Wands": "deck-images/w06.jpg",
  "Seven of Wands": "deck-images/w07.jpg",
  "Eight of Wands": "deck-images/w08.jpg",
  "Nine of Wands": "deck-images/w09.jpg",
  "Ten of Wands": "deck-images/w10.jpg",
  "Page of Wands": "deck-images/w11.jpg",
  "Knight of Wands": "deck-images/w12.jpg",
  "Queen of Wands": "deck-images/w13.jpg",
  "King of Wands": "deck-images/w14.jpg",
  // Pentacles
  "Ace of Pentacles": "deck-images/p01.jpg",
  "Two of Pentacles": "deck-images/p02.jpg",
  "Three of Pentacles": "deck-images/p03.jpg",
  "Four of Pentacles": "deck-images/p04.jpg",
  "Five of Pentacles": "deck-images/p05.jpg",
  "Six of Pentacles": "deck-images/p06.jpg",
  "Seven of Pentacles": "deck-images/p07.jpg",
  "Eight of Pentacles": "deck-images/p08.jpg",
  "Nine of Pentacles": "deck-images/p09.jpg",
  "Ten of Pentacles": "deck-images/p10.jpg",
  "Page of Pentacles": "deck-images/p11.jpg",
  "Knight of Pentacles": "deck-images/p12.jpg",
  "Queen of Pentacles": "deck-images/p13.jpg",
  "King of Pentacles": "deck-images/p14.jpg",
};

/** Return image URL for a card name, or null if not found */
function getCardImage(cardName) {
  return CARD_IMAGES[cardName] || null;
}
